[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture"

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "script-src 'self' 'unsafe-inline'"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
